baseurl = "https://jamesopt.github.io"
title = "1+1>2"
languageCode = "zh-CN"
disqusShortname = "jamesho-1"
copyright = "Copyright (c) 2019 - 2020, Steve Francia; all rights reserved."
MetaDataFormat = "toml"
googleAnalytics = "UA-7131036-1"
enableemoji = true
hasCJKLanguage = false

[author]
    name = "Steve Francia"

[indexes]
    tag = "tags"
    topic = "topics"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"
